Calculate weights: 7.152557373046875e-07
Load graphs: 153.7341296672821
elapsed CPM 2.4815726280212402 seconds cpm 0
elapsed CPM 2.584962844848633 seconds cpm 0
elapsed CPM 862.0272164344788 seconds cpm 40.0
elapsed CPM 972.9922358989716 seconds cpm 355563.0
elapsed CPM 1098.274888753891 seconds cpm 3257758.7000022135
elapsed CPM 1155.8520381450653 seconds cpm 9021033.909981258
elapsed CPM 1207.5129973888397 seconds cpm 17889869.474997
elapsed CPM 1232.2896156311035 seconds cpm 26081546.265599318
elapsed CPM 2.384185791015625e-06 seconds cpm 0
elapsed CPM 1196.1994111537933 seconds cpm 39837.150000393936
elapsed CPM 1198.0057411193848 seconds cpm 210643.0
elapsed CPM 1173.8425388336182 seconds cpm 600587.5
elapsed CPM 1224.791571855545 seconds cpm 1546044.5
elapsed CPM 1313.7831230163574 seconds cpm 6053129.900006746
elapsed CPM 1270.7209842205048 seconds cpm 12288537.36001144
elapsed CPM 1323.906492948532 seconds cpm 20893034.696000732
Exception in thread Thread-31:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 405, in _handle_workers
    pool._maintain_pool()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 246, in _maintain_pool
    self._repopulate_pool()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

